name: Build rules

on:
  push:
    branches:
      - master
    paths:
      - "build.bash"
      - "hosts.txt"

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'green1052/no-coupang-partners' && github.event.head_commit.author.email != 'action@github.com'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build
        run: node build.js

      - name: Commit
        run: |
          git add filters-share/search.txt
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Build rules" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}